
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: taptap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ton-demo-be:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
volumes:
  postgres_data:
